/**
 * SHOPORA — Production-Grade Database Seeder
 * Populates 8 categories, 50+ realistic products across 5 major departments,
 * verified customer reviews, multiple delivery addresses, and pre-configured demo users.
 */

const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');

dotenv.config();

const Category = require('../models/Category');
const Product = require('../models/Product');
const User = require('../models/User');
const Wishlist = require('../models/Wishlist');
const Order = require('../models/Order');
const Review = require('../models/Review');
const Notification = require('../models/Notification');
const Cart = require('../models/Cart');
const Offer = require('../models/Offer');

const connectDB = async () => {
  try {
    const conn = await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/novamart');
    console.log(`[Database] Connected: ${conn.connection.host}`);
  } catch (error) {
    console.error(`Error connecting to MongoDB: ${error.message}`);
    process.exit(1);
  }
};

const categoriesData = [
  {
    name: 'Mobiles & Tablets',
    slug: 'mobiles-and-tablets',
    icon: '📱',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    description: 'Flagship smartphones, pro tablets, and cellular accessories with authentic warranty.',
    displayOrder: 1,
  },
  {
    name: 'Laptops & Computing',
    slug: 'laptops-and-computing',
    icon: '💻',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80',
    description: 'Workstations, ultrabooks, gaming rigs, and high-performance creative hardware.',
    displayOrder: 2,
  },
  {
    name: 'Audio & Headphones',
    slug: 'audio-and-headphones',
    icon: '🎧',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    description: 'Audiophile active noise-cancelling headphones, true wireless earbuds, and speakers.',
    displayOrder: 3,
  },
  {
    name: 'Smart Home & Appliances',
    slug: 'smart-home-and-appliances',
    icon: '🏠',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    description: 'Intelligent espresso machines, robotic vacuums, climate care, and ambient living.',
    displayOrder: 4,
  },
  {
    name: 'Fashion & Apparel',
    slug: 'fashion-and-apparel',
    icon: '👔',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&auto=format&fit=crop&q=80',
    description: 'Designer apparel, tailored outerwear, luxury timepieces, and leather goods.',
    displayOrder: 5,
  },
  {
    name: 'Footwear & Sneakers',
    slug: 'footwear-and-sneakers',
    icon: '👟',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    description: 'Iconic performance running shoes, collectible sneakers, and casual streetwear.',
    displayOrder: 6,
  },
  {
    name: 'Beauty & Personal Care',
    slug: 'beauty-and-personal-care',
    icon: '✨',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    description: 'High-velocity styling dryers, ultrasonic skincare devices, and luxury grooming.',
    displayOrder: 7,
  },
  {
    name: 'Sports & Fitness',
    slug: 'sports-and-fitness',
    icon: '🏋️',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    description: 'Aerodynamic cycling helmets, smart adjustable weights, and cardio equipment.',
    displayOrder: 8,
  },
];

const seedDatabase = async () => {
  try {
    await connectDB();

    console.log('[Seed] Clearing existing collections...');
    await Promise.all([
      Category.deleteMany({}),
      Product.deleteMany({}),
      User.deleteMany({}),
      Wishlist.deleteMany({}),
      Order.deleteMany({}),
      Review.deleteMany({}),
      Notification.deleteMany({}),
      Cart.deleteMany({}),
      Offer.deleteMany({}),
    ]);

    console.log('[Seed] Seeding 8 categories...');
    const insertedCategories = await Category.insertMany(categoriesData);
    const catMap = {};
    insertedCategories.forEach((c) => {
      catMap[c.slug] = c;
    });

    console.log('[Seed] Seeding 50+ realistic products...');
    const productsData = [
      // 1. MOBILES & TABLETS
      {
        name: 'Apple iPhone 15 Pro Max (256GB Titanium)',
        brand: 'Apple',
        category: catMap['mobiles-and-tablets']._id,
        categoryName: 'Mobiles & Tablets',
        subcategory: 'Smartphones',
        price: 1199.99,
        originalPrice: 1299.99,
        discount: 8,
        image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
        images: [
          'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
        ],
        stock: 35,
        sku: 'APL-IP15PM-256',
        rating: 4.9,
        reviewCount: 384,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: true,
        offerText: 'Instant $100 off with select bank cards',
        specifications: [
          { key: 'Processor', value: 'Apple A17 Pro (3nm)' },
          { key: 'Display', value: '6.7-inch Super Retina XDR 120Hz OLED' },
          { key: 'Camera', value: '48MP Main + 12MP 5x Telephoto + 12MP Ultra-Wide' },
          { key: 'Build', value: 'Aerospace-Grade Titanium Frame' },
        ],
        description: 'iPhone 15 Pro Max forged in aerospace-grade titanium with the groundbreaking A17 Pro chip and customizable Action button.',
      },
      {
        name: 'Samsung Galaxy S24 Ultra AI (512GB Titanium Gray)',
        brand: 'Samsung',
        category: catMap['mobiles-and-tablets']._id,
        categoryName: 'Mobiles & Tablets',
        subcategory: 'Smartphones',
        price: 1249.99,
        originalPrice: 1419.99,
        discount: 12,
        image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&auto=format&fit=crop&q=80',
        stock: 28,
        sku: 'SAM-S24U-512',
        rating: 4.8,
        reviewCount: 290,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: true,
        isNew: true,
        offerText: 'Includes complimentary Galaxy Buds FE and S-Pen',
        specifications: [
          { key: 'Processor', value: 'Snapdragon 8 Gen 3 for Galaxy' },
          { key: 'Display', value: '6.8-inch Dynamic AMOLED 2X QHD+ 2600 nits' },
          { key: 'Camera', value: '200MP Quad Telephoto with 100x Space Zoom' },
          { key: 'Battery', value: '5000 mAh with 45W Fast Charging' },
        ],
        description: 'Meet Galaxy S24 Ultra with Galaxy AI, titanium shield exterior, and embedded Bluetooth S-Pen.',
      },
      {
        name: 'Google Pixel 8 Pro (128GB Obsidian Black)',
        brand: 'Google',
        category: catMap['mobiles-and-tablets']._id,
        categoryName: 'Mobiles & Tablets',
        subcategory: 'Smartphones',
        price: 799.99,
        originalPrice: 999.99,
        discount: 20,
        image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
        stock: 22,
        sku: 'GGL-PX8P-128',
        rating: 4.7,
        reviewCount: 175,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Special Flash Deal: 20% off today only',
        specifications: [
          { key: 'Processor', value: 'Google Tensor G3' },
          { key: 'Display', value: '6.7-inch Super Actua OLED 1-120Hz' },
          { key: 'Camera', value: '50MP Octa PD Main with Magic Editor' },
        ],
        description: 'Google Pixel 8 Pro is the all-pro phone engineered by Google with state-of-the-art computational photography.',
      },
      {
        name: 'Apple iPad Pro 13-inch M4 Ultra Retina XDR',
        brand: 'Apple',
        category: catMap['mobiles-and-tablets']._id,
        categoryName: 'Mobiles & Tablets',
        subcategory: 'Tablets',
        price: 1299.00,
        originalPrice: 1399.00,
        discount: 7,
        image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
        stock: 18,
        sku: 'APL-IPAD13-M4',
        rating: 4.9,
        reviewCount: 142,
        isFeatured: true,
        isPremium: true,
        isTrending: false,
        isNew: true,
        offerText: 'Free Apple Pencil Pro compatible setup support',
        specifications: [
          { key: 'Chipset', value: 'Apple M4 Chip with 10-core GPU' },
          { key: 'Display', value: 'Tandem OLED Ultra Retina XDR' },
          { key: 'Thickness', value: 'Ultra-thin 5.1mm' },
        ],
        description: 'The thinnest Apple product ever made, delivering insane performance with the M4 silicon and tandem OLED technology.',
      },
      {
        name: 'Samsung Galaxy Tab S9 Ultra (14.6-inch Dynamic AMOLED)',
        brand: 'Samsung',
        category: catMap['mobiles-and-tablets']._id,
        categoryName: 'Mobiles & Tablets',
        subcategory: 'Tablets',
        price: 999.99,
        originalPrice: 1199.99,
        discount: 17,
        image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&auto=format&fit=crop&q=80',
        stock: 15,
        sku: 'SAM-TABS9U',
        rating: 4.8,
        reviewCount: 98,
        isFeatured: false,
        isPremium: true,
        isTrending: false,
        isDeal: true,
        isNew: false,
        offerText: 'Includes S-Pen in box',
        specifications: [
          { key: 'Screen', value: '14.6-inch Dynamic AMOLED 2X' },
          { key: 'Water Resistance', value: 'IP68 Certified' },
        ],
        description: 'Cinematic 14.6-inch tablet designed for elite creative multitasking and media immersion.',
      },

      // 2. LAPTOPS & COMPUTING
      {
        name: 'Apple MacBook Pro 16-inch M3 Max (36GB / 1TB SSD)',
        brand: 'Apple',
        category: catMap['laptops-and-computing']._id,
        categoryName: 'Laptops & Computing',
        subcategory: 'Laptops',
        price: 3499.00,
        originalPrice: 3799.00,
        discount: 8,
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
        stock: 12,
        sku: 'APL-MBP16-M3M',
        rating: 4.9,
        reviewCount: 220,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: true,
        offerText: 'Official 3-year AppleCare warranty included',
        specifications: [
          { key: 'CPU', value: 'Apple M3 Max 14-Core CPU / 30-Core GPU' },
          { key: 'Memory', value: '36GB Unified Memory' },
          { key: 'Display', value: 'Liquid Retina XDR with 1600 nits peak brightness' },
        ],
        description: 'The ultimate powerhouse workstation for 3D animation, code compilation, and 8K video color grading.',
      },
      {
        name: 'Dell XPS 15 9530 InfinityEdge OLED Creator Edition',
        brand: 'Dell',
        category: catMap['laptops-and-computing']._id,
        categoryName: 'Laptops & Computing',
        subcategory: 'Laptops',
        price: 1899.99,
        originalPrice: 2299.99,
        discount: 17,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
        stock: 14,
        sku: 'DEL-XPS15-9530',
        rating: 4.7,
        reviewCount: 160,
        isFeatured: true,
        isPremium: true,
        isTrending: false,
        isDeal: true,
        isNew: false,
        offerText: 'Save $400 this week on Creator Edition',
        specifications: [
          { key: 'Processor', value: 'Intel Core i9-13900H (14 cores)' },
          { key: 'GPU', value: 'NVIDIA GeForce RTX 4070 8GB GDDR6' },
          { key: 'Screen', value: '3.5K 3456x2160 OLED Touch Display' },
        ],
        description: 'CNC machined aluminum chassis paired with carbon fiber palm rests and breathtaking InfinityEdge visuals.',
      },
      {
        name: 'ASUS ROG Zephyrus G16 OLED Gaming Laptop',
        brand: 'ASUS',
        category: catMap['laptops-and-computing']._id,
        categoryName: 'Laptops & Computing',
        subcategory: 'Gaming Laptops',
        price: 2199.99,
        originalPrice: 2499.99,
        discount: 12,
        image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
        stock: 10,
        sku: 'ASU-ROG-G16',
        rating: 4.8,
        reviewCount: 110,
        isFeatured: false,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: true,
        offerText: '3 Months Xbox Game Pass Ultimate included',
        specifications: [
          { key: 'Processor', value: 'Intel Core Ultra 9 185H' },
          { key: 'Graphics', value: 'NVIDIA RTX 4080 12GB' },
          { key: 'Display', value: '2.5K 240Hz 0.2ms ROG Nebula OLED' },
        ],
        description: 'Ultra-slim 1.49cm aluminum CNC gaming beast with ROG Nebula OLED display.',
      },
      {
        name: 'LG UltraGear 32-inch 4K OLED Gaming Monitor (240Hz)',
        brand: 'LG',
        category: catMap['laptops-and-computing']._id,
        categoryName: 'Laptops & Computing',
        subcategory: 'Monitors',
        price: 1199.99,
        originalPrice: 1399.99,
        discount: 14,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
        stock: 8,
        sku: 'LG-32GS95UE',
        rating: 4.9,
        reviewCount: 75,
        isFeatured: false,
        isPremium: true,
        isTrending: true,
        isDeal: true,
        isNew: true,
        offerText: 'Dual-Hz Technology: switch between 4K 240Hz and FHD 480Hz',
        specifications: [
          { key: 'Panel', value: '31.5-inch 4K UHD OLED 0.03ms' },
          { key: 'Audio', value: 'Pixel Sound Acoustic Screen' },
        ],
        description: 'World-first Dual-Hz OLED monitor allowing instant toggling between ultra-crisp 4K 240Hz and competitive 480Hz FHD.',
      },
      {
        name: 'Logitech MX Master 3S Wireless Performance Mouse',
        brand: 'Logitech',
        category: catMap['laptops-and-computing']._id,
        categoryName: 'Laptops & Computing',
        subcategory: 'Accessories',
        price: 99.99,
        originalPrice: 119.99,
        discount: 17,
        image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
        stock: 45,
        sku: 'LOG-MXM3S-GRY',
        rating: 4.9,
        reviewCount: 520,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Best seller in productivity gear',
        specifications: [
          { key: 'Sensor', value: '8000 DPI Darkfield Tracks on Glass' },
          { key: 'Scroll Wheel', value: 'MagSpeed Electromagnetic 1000 lines/sec' },
        ],
        description: 'Iconic ergonomic tool with quiet clicks, cross-computer Flow control, and precision electromagnetic wheel.',
      },

      // 3. AUDIO & HEADPHONES
      {
        name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
        brand: 'Sony',
        category: catMap['audio-and-headphones']._id,
        categoryName: 'Audio & Headphones',
        subcategory: 'Over-Ear Headphones',
        price: 348.00,
        originalPrice: 399.99,
        discount: 13,
        image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
        stock: 30,
        sku: 'SNY-WH1000XM5-BLK',
        rating: 4.8,
        reviewCount: 410,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Special bundle: Free protective travel case',
        specifications: [
          { key: 'Processors', value: 'Integrated Processor V1 + HD QN1' },
          { key: 'Microphones', value: '8 microphones with Auto NC Optimizer' },
          { key: 'Battery', value: '30 hours with fast 3-min charge for 3 hours' },
        ],
        description: 'Industry-leading noise cancellation rewritten with dual processors and four beamforming mics for crystal clear calls.',
      },
      {
        name: 'Bose QuietComfort Ultra Spatial Audio Headphones',
        brand: 'Bose',
        category: catMap['audio-and-headphones']._id,
        categoryName: 'Audio & Headphones',
        subcategory: 'Over-Ear Headphones',
        price: 379.00,
        originalPrice: 429.00,
        discount: 12,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        stock: 25,
        sku: 'BOS-QCU-WHT',
        rating: 4.8,
        reviewCount: 280,
        isFeatured: true,
        isPremium: true,
        isTrending: false,
        isDeal: false,
        isNew: true,
        offerText: 'Bose Immersive Audio Spatial Experience',
        specifications: [
          { key: 'Spatial Sound', value: 'Bose Immersive Audio Technology' },
          { key: 'Materials', value: 'Ultra-plush protein leather ear cushions' },
        ],
        description: 'High-fidelity audio breakthrough featuring revolutionary spatialized audio that brings what you hear right in front of you.',
      },
      {
        name: 'Apple AirPods Pro (2nd Generation with USB-C)',
        brand: 'Apple',
        category: catMap['audio-and-headphones']._id,
        categoryName: 'Audio & Headphones',
        subcategory: 'Earbuds',
        price: 199.99,
        originalPrice: 249.00,
        discount: 20,
        image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80',
        stock: 50,
        sku: 'APL-APP2-USBC',
        rating: 4.9,
        reviewCount: 650,
        isFeatured: true,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: true,
        offerText: 'Save $50 on America’s top rated earbuds',
        specifications: [
          { key: 'Chip', value: 'Apple H2 Headphone Chip' },
          { key: 'Case', value: 'MagSafe Case (USB-C) with Speaker and Lanyard loop' },
        ],
        description: 'Up to 2x more Active Noise Cancellation, Adaptive Audio, and Personalized Spatial Audio with dynamic head tracking.',
      },
      {
        name: 'Marshall Stanmore III Bluetooth Wireless Home Speaker',
        brand: 'Marshall',
        category: catMap['audio-and-headphones']._id,
        categoryName: 'Audio & Headphones',
        subcategory: 'Speakers',
        price: 329.99,
        originalPrice: 379.99,
        discount: 13,
        image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
        stock: 14,
        sku: 'MSH-STAN3-BLK',
        rating: 4.7,
        reviewCount: 135,
        isFeatured: false,
        isPremium: true,
        isTrending: false,
        isDeal: false,
        isNew: false,
        offerText: 'Iconic vintage styling with modern room-filling stereo',
        specifications: [
          { key: 'Amplification', value: '50 Watt Class D for Woofer + Two 15W for Tweeters' },
          { key: 'Frequency', value: '45–20,000 Hz' },
        ],
        description: 'Re-engineered with a wider stereo soundstage and brass control knobs for pure analog tactile enjoyment.',
      },
      {
        name: 'Sennheiser Momentum True Wireless 4 Earbuds',
        brand: 'Sennheiser',
        category: catMap['audio-and-headphones']._id,
        categoryName: 'Audio & Headphones',
        subcategory: 'Earbuds',
        price: 249.95,
        originalPrice: 299.95,
        discount: 17,
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
        stock: 18,
        sku: 'SNH-MTW4-COP',
        rating: 4.8,
        reviewCount: 92,
        isFeatured: false,
        isPremium: true,
        isTrending: false,
        isDeal: true,
        isNew: true,
        offerText: 'Snapdragon Sound and Lossless Audio Support',
        specifications: [
          { key: 'Driver', value: 'TrueResponse Transducer 7mm' },
          { key: 'Codecs', value: 'aptX Lossless, LE Audio, Auracast' },
        ],
        description: 'Audiophile grade acoustic architecture tuned for uncompromising frequency precision.',
      },

      // 4. SMART HOME & APPLIANCES
      {
        name: 'Dyson V15 Detect Cordless Vacuum Cleaner',
        brand: 'Dyson',
        category: catMap['smart-home-and-appliances']._id,
        categoryName: 'Smart Home & Appliances',
        subcategory: 'Vacuums',
        price: 649.99,
        originalPrice: 749.99,
        discount: 13,
        image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80',
        stock: 16,
        sku: 'DYS-V15-DET',
        rating: 4.8,
        reviewCount: 310,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Laser illumination reveals microscopic dust on hard floors',
        specifications: [
          { key: 'Suction Power', value: '240 Air Watts' },
          { key: 'Filtration', value: 'Whole-machine HEPA 99.99% to 0.3 microns' },
        ],
        description: 'Dyson’s most powerful, intelligent cordless vacuum with piezo sensor sizing and counting particles in real time.',
      },
      {
        name: 'De’Longhi Magnifica S Fully Automatic Espresso Machine',
        brand: "De'Longhi",
        category: catMap['smart-home-and-appliances']._id,
        categoryName: 'Smart Home & Appliances',
        subcategory: 'Coffee & Kitchen',
        price: 799.00,
        originalPrice: 999.00,
        discount: 20,
        image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
        stock: 11,
        sku: 'DLG-MAG-S',
        rating: 4.9,
        reviewCount: 240,
        isFeatured: true,
        isPremium: true,
        isTrending: false,
        isDeal: true,
        isNew: false,
        offerText: 'Includes 1kg Artisanal Italian Espresso Beans',
        specifications: [
          { key: 'Pressure', value: '15 Bar Italian Pump' },
          { key: 'Grinder', value: 'Integrated Stainless Steel Conical Burr with 13 settings' },
        ],
        description: 'Bean-to-cup luxury espresso, cappuccino, and latte with manual traditional milk frother steam wand.',
      },
      {
        name: 'Philips Digital Airfryer XXL with Rapid Air Technology',
        brand: 'Philips',
        category: catMap['smart-home-and-appliances']._id,
        categoryName: 'Smart Home & Appliances',
        subcategory: 'Coffee & Kitchen',
        price: 199.99,
        originalPrice: 249.99,
        discount: 20,
        image: 'https://images.unsplash.com/photo-1586208958839-06c17cacdf08?w=800&auto=format&fit=crop&q=80',
        stock: 28,
        sku: 'PHL-AF-XXL',
        rating: 4.8,
        reviewCount: 380,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Fat Removal technology extracts excess fat for healthier meals',
        specifications: [
          { key: 'Capacity', value: '7.3 Liters (Cooks whole chicken)' },
          { key: 'Power', value: '2225 Watts Instant Heat' },
        ],
        description: 'The healthiest way to fry with little to no added oil, crisping exterior while keeping interior succulent.',
      },
      {
        name: 'iRobot Roomba j9+ Self-Emptying Robot Vacuum',
        brand: 'iRobot',
        category: catMap['smart-home-and-appliances']._id,
        categoryName: 'Smart Home & Appliances',
        subcategory: 'Vacuums',
        price: 699.99,
        originalPrice: 899.99,
        discount: 22,
        image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
        stock: 9,
        sku: 'IROB-J9P-AUTO',
        rating: 4.7,
        reviewCount: 165,
        isFeatured: false,
        isPremium: true,
        isTrending: true,
        isDeal: true,
        isNew: true,
        offerText: 'Clean Base holds up to 60 days of debris',
        specifications: [
          { key: 'Navigation', value: 'PrecisionVision AI Obstacle Avoidance' },
          { key: 'Suction', value: '100% more suction power than previous generation' },
        ],
        description: 'Identifies and avoids pet waste and cords, returning to its wood-finish dock to empty itself automatically.',
      },
      {
        name: 'Philips Hue White and Color Ambiance Smart Starter Kit',
        brand: 'Philips',
        category: catMap['smart-home-and-appliances']._id,
        categoryName: 'Smart Home & Appliances',
        subcategory: 'Smart Lighting',
        price: 159.99,
        originalPrice: 199.99,
        discount: 20,
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80',
        stock: 35,
        sku: 'PHL-HUE-STRT4',
        rating: 4.8,
        reviewCount: 420,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: '16 Million Colors with Apple HomeKit & Alexa integration',
        specifications: [
          { key: 'Pack', value: '4 Smart Bulbs + 1 Hue Bridge Hub' },
          { key: 'Brightness', value: '1100 Lumens per bulb (75W equivalent)' },
        ],
        description: 'Transform home ambience instantly with voice-controlled smart lighting syncable to music and screen entertainment.',
      },

      // 5. FASHION & APPAREL
      {
        name: 'Omega Seamaster Diver 300M Co-Axial Master Chronometer',
        brand: 'Omega',
        category: catMap['fashion-and-apparel']._id,
        categoryName: 'Fashion & Apparel',
        subcategory: 'Luxury Watches',
        price: 4900.00,
        originalPrice: 5400.00,
        discount: 9,
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
        stock: 5,
        sku: 'OMG-SM-300M',
        rating: 4.9,
        reviewCount: 65,
        isFeatured: true,
        isPremium: true,
        isTrending: false,
        isDeal: false,
        isNew: false,
        offerText: '5-year international manufacturer warranty & certificate',
        specifications: [
          { key: 'Movement', value: 'Omega Calibre 8800 Self-Winding' },
          { key: 'Case Diameter', value: '42mm Stainless Steel with Ceramic Bezel' },
          { key: 'Water Resistance', value: '300 meters / 1000 feet' },
        ],
        description: 'Legendary maritime timepiece chosen by secret agents and luxury collectors worldwide since 1993.',
      },
      {
        name: 'Ralph Lauren Slim Fit Oxford Cotton Shirt',
        brand: 'Ralph Lauren',
        category: catMap['fashion-and-apparel']._id,
        categoryName: 'Fashion & Apparel',
        subcategory: 'Shirts',
        price: 115.00,
        originalPrice: 145.00,
        discount: 21,
        image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
        stock: 40,
        sku: 'RL-OXF-SLM-BLU',
        rating: 4.7,
        reviewCount: 210,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: '100% Breathable Combed Cotton',
        specifications: [
          { key: 'Material', value: '100% Oxford Weave Cotton' },
          { key: 'Fit', value: 'Tailored Slim Fit' },
        ],
        description: 'An iconic staple of preppy American tailoring, crafted from breathable woven cotton with signature pony embroidery.',
      },
      {
        name: 'Bellroy Classic Leather Tech Backpack (20L)',
        brand: 'Bellroy',
        category: catMap['fashion-and-apparel']._id,
        categoryName: 'Fashion & Apparel',
        subcategory: 'Bags & Accessories',
        price: 149.00,
        originalPrice: 179.00,
        discount: 17,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
        stock: 25,
        sku: 'BEL-BKPK-20L',
        rating: 4.8,
        reviewCount: 155,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: true,
        offerText: 'Padded laptop pocket holds up to 16-inch MacBook',
        specifications: [
          { key: 'Fabric', value: 'Durable water-resistant woven fabric and eco-certified leather' },
          { key: 'Capacity', value: '20 Liters' },
        ],
        description: 'Clean silhouette designed for urban professionals with smart internal organization and contoured lumbar support.',
      },
      {
        name: 'Levi’s 511 Slim Fit Stretch Denim Jeans',
        brand: "Levi's",
        category: catMap['fashion-and-apparel']._id,
        categoryName: 'Fashion & Apparel',
        subcategory: 'Jeans',
        price: 69.99,
        originalPrice: 89.99,
        discount: 22,
        image: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
        stock: 45,
        sku: 'LEV-511-SLM',
        rating: 4.7,
        reviewCount: 480,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Built with Levi’s Flex Advanced Stretch',
        specifications: [
          { key: 'Material', value: '99% Cotton, 1% Elastane' },
          { key: 'Leg Opening', value: '14.5-inch Slim' },
        ],
        description: 'A modern slim cut with room to move, upgraded with premium flex stretch for all-day mobility.',
      },

      // 6. FOOTWEAR & SNEAKERS
      {
        name: 'Nike Air Jordan 1 Retro High OG (Chicago Reimagined)',
        brand: 'Nike',
        category: catMap['footwear-and-sneakers']._id,
        categoryName: 'Footwear & Sneakers',
        subcategory: 'Sneakers',
        price: 180.00,
        originalPrice: 210.00,
        discount: 14,
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
        stock: 20,
        sku: 'NKE-AJ1-CHI',
        rating: 4.9,
        reviewCount: 520,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: true,
        offerText: '100% Verified Authentic Jordan Brand stock',
        specifications: [
          { key: 'Upper', value: 'Premium Aged Leather with Cracked Finish' },
          { key: 'Cushioning', value: 'Encapsulated Air-Sole Unit' },
        ],
        description: 'The Holy Grail of sneaker culture honoring the iconic 1985 silhouette with vintage aesthetic detailing.',
      },
      {
        name: 'Adidas Ultraboost Light Running Shoes',
        brand: 'Adidas',
        category: catMap['footwear-and-sneakers']._id,
        categoryName: 'Footwear & Sneakers',
        subcategory: 'Running Shoes',
        price: 149.99,
        originalPrice: 189.99,
        discount: 21,
        image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
        stock: 35,
        sku: 'ADI-UBL-BLK',
        rating: 4.8,
        reviewCount: 340,
        isFeatured: true,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: '30% Lighter BOOST material with extreme energy return',
        specifications: [
          { key: 'Midsole', value: 'Light BOOST Foam' },
          { key: 'Outsole', value: 'Continental Better Rubber' },
        ],
        description: 'Experience epic energy return with adidas’s lightest Ultraboost yet, engineered for marathon endurance.',
      },
      {
        name: 'New Balance 990v6 Made in USA Heritage Sneaker',
        brand: 'New Balance',
        category: catMap['footwear-and-sneakers']._id,
        categoryName: 'Footwear & Sneakers',
        subcategory: 'Sneakers',
        price: 199.99,
        originalPrice: 219.99,
        discount: 9,
        image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80',
        stock: 18,
        sku: 'NB-990V6-GRY',
        rating: 4.9,
        reviewCount: 190,
        isFeatured: false,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: true,
        offerText: 'Crafted in USA with domestic value of 70% or more',
        specifications: [
          { key: 'Cushioning', value: 'FuelCell Foam + ENCAP Midsole' },
          { key: 'Upper', value: 'Pigskin Suede and Mesh' },
        ],
        description: 'The flagship grey dad shoe elevated into ultra-comfortable high fashion with FuelCell propulsion technology.',
      },

      // 7. BEAUTY & PERSONAL CARE
      {
        name: 'Dyson Supersonic Nural Intelligent Hair Dryer',
        brand: 'Dyson',
        category: catMap['beauty-and-personal-care']._id,
        categoryName: 'Beauty & Personal Care',
        subcategory: 'Hair Styling',
        price: 499.99,
        originalPrice: 549.99,
        discount: 9,
        image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
        stock: 14,
        sku: 'DYS-NURL-TEAL',
        rating: 4.9,
        reviewCount: 180,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: true,
        offerText: 'Scalp Protect Mode automatically adjusts temperature',
        specifications: [
          { key: 'Motor', value: 'Dyson Digital Motor V9 (110,000 RPM)' },
          { key: 'Sensors', value: 'Time of Flight Scalp Distance Sensor' },
        ],
        description: 'Intelligent heat control prevents extreme heat damage to preserve natural shine and protect scalp barrier.',
      },
      {
        name: 'Oral-B iO Series 10 Rechargeable Electric Toothbrush',
        brand: 'Oral-B',
        category: catMap['beauty-and-personal-care']._id,
        categoryName: 'Beauty & Personal Care',
        subcategory: 'Oral Care',
        price: 299.99,
        originalPrice: 379.99,
        discount: 21,
        image: 'https://images.unsplash.com/photo-1559591937-e1032c7e0c4a?w=800&auto=format&fit=crop&q=80',
        stock: 22,
        sku: 'ORB-IO10-BLK',
        rating: 4.8,
        reviewCount: 220,
        isFeatured: false,
        isPremium: true,
        isTrending: false,
        isDeal: true,
        isNew: false,
        offerText: 'iSense Smart Charger with live brushing guidance',
        specifications: [
          { key: 'Action', value: 'Micro-vibrating bristles with round head' },
          { key: 'Modes', value: '7 Smart Cleaning Modes' },
        ],
        description: 'Revolutionary magnetic iO technology delivers professional clean feeling and personalized real-time coaching.',
      },

      // 8. SPORTS & FITNESS
      {
        name: 'Bowflex SelectTech 552 Adjustable Dumbbells (Pair)',
        brand: 'Bowflex',
        category: catMap['sports-and-fitness']._id,
        categoryName: 'Sports & Fitness',
        subcategory: 'Fitness & Gym',
        price: 379.00,
        originalPrice: 429.00,
        discount: 12,
        image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
        stock: 12,
        sku: 'BWF-ST552-PR',
        rating: 4.8,
        reviewCount: 310,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: false,
        offerText: 'Replaces 15 sets of weights in one compact system',
        specifications: [
          { key: 'Weight Range', value: '5 to 52.5 lbs per dumbbell' },
          { key: 'Dial System', value: 'Rapid turn selection dial' },
        ],
        description: 'With just the turn of a dial, adjust resistance from 5 lbs up to 52.5 lbs per dumbbell for versatile home workouts.',
      },
      {
        name: 'Garmin Forerunner 965 AMOLED GPS Smartwatch',
        brand: 'Garmin',
        category: catMap['sports-and-fitness']._id,
        categoryName: 'Sports & Fitness',
        subcategory: 'Sports Tech',
        price: 549.99,
        originalPrice: 599.99,
        discount: 8,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
        stock: 16,
        sku: 'GRM-FR965-BLK',
        rating: 4.9,
        reviewCount: 145,
        isFeatured: true,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: true,
        offerText: 'Titanium bezel with built-in full-color maps',
        specifications: [
          { key: 'Screen', value: '1.4-inch AMOLED Touchscreen 454x454' },
          { key: 'Battery', value: 'Up to 23 days in smartwatch mode / 31 hrs in GPS' },
        ],
        description: 'Premium titanium running and triathlon smartwatch with brilliant AMOLED screen and advanced training dynamics.',
      },
      {
        name: 'Theragun PRO Plus 6-in-1 Percussive Therapy Device',
        brand: 'Therabody',
        category: catMap['sports-and-fitness']._id,
        categoryName: 'Sports & Fitness',
        subcategory: 'Recovery',
        price: 499.00,
        originalPrice: 599.00,
        discount: 17,
        image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
        stock: 14,
        sku: 'THB-PRO-PLUS',
        rating: 4.8,
        reviewCount: 95,
        isFeatured: false,
        isPremium: true,
        isTrending: false,
        isDeal: true,
        isNew: true,
        offerText: 'Combines deep percussive therapy with near-infrared LED light',
        specifications: [
          { key: 'Amplitude', value: '16mm deep muscle treatment' },
          { key: 'Features', value: 'Vibration therapy, thermal heat, and breathwork' },
        ],
        description: 'Elite recovery tool used by world champions, combining 16mm percussive massage with infrared light and heart rate sensor.',
      },
    ];

    // Additional products to ensure 50+ total count across all categories
    const extraProducts = [
      {
        name: 'Sony Alpha A7 IV Full-Frame Mirrorless Camera (Body)',
        brand: 'Sony',
        category: catMap['laptops-and-computing']._id,
        categoryName: 'Laptops & Computing',
        subcategory: 'Cameras',
        price: 2298.00,
        originalPrice: 2499.99,
        discount: 8,
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
        stock: 7,
        sku: 'SNY-A7M4-BODY',
        rating: 4.9,
        reviewCount: 165,
        isFeatured: true,
        isPremium: true,
        isTrending: false,
        isDeal: false,
        isNew: false,
        offerText: '33MP Exmor R CMOS Sensor with 4K 60p 10-bit recording',
        specifications: [{ key: 'Sensor', value: '33MP Full-Frame Exmor R' }, { key: 'Autofocus', value: '759 phase-detection points' }],
        description: 'The benchmark hybrid mirrorless camera for breathtaking photography and cinematic video production.',
      },
      {
        name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
        brand: 'Keychron',
        category: catMap['laptops-and-computing']._id,
        categoryName: 'Laptops & Computing',
        subcategory: 'Keyboards',
        price: 199.99,
        originalPrice: 229.99,
        discount: 13,
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
        stock: 30,
        sku: 'KEY-Q1PRO-RD',
        rating: 4.8,
        reviewCount: 140,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: true,
        offerText: 'Full CNC Machined Aluminum Body with QMK/VIA support',
        specifications: [{ key: 'Structure', value: 'Double Gasket Mount' }, { key: 'Switches', value: 'Hot-swappable Gateron Jupiter Red' }],
        description: 'Audiophile mechanical typing experience with South-facing RGB and Bluetooth 5.1 multi-device connectivity.',
      },
      {
        name: 'Sonos Move 2 Portable Smart Speaker with Spatial Audio',
        brand: 'Sonos',
        category: catMap['audio-and-headphones']._id,
        categoryName: 'Audio & Headphones',
        subcategory: 'Speakers',
        price: 399.00,
        originalPrice: 449.00,
        discount: 11,
        image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
        stock: 15,
        sku: 'SON-MOVE2-BLK',
        rating: 4.8,
        reviewCount: 115,
        isFeatured: false,
        isPremium: true,
        isTrending: true,
        isDeal: false,
        isNew: true,
        offerText: 'Up to 24 hours of playback on a single charge',
        specifications: [{ key: 'Water Resistance', value: 'IP56 Weatherproof' }, { key: 'Connectivity', value: 'Wi-Fi 6 + Bluetooth 5.0' }],
        description: 'Stereo sound on the move with automatic Trueplay tuning adjusting sound to your exact outdoor or indoor surroundings.',
      },
      {
        name: 'Nike Sportswear Tech Fleece Windrunner Full-Zip Hoodie',
        brand: 'Nike',
        category: catMap['fashion-and-apparel']._id,
        categoryName: 'Fashion & Apparel',
        subcategory: 'Jackets',
        price: 125.00,
        originalPrice: 145.00,
        discount: 14,
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
        stock: 35,
        sku: 'NKE-TECH-FLC',
        rating: 4.8,
        reviewCount: 310,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Lightweight warmth with signature chevron design lines',
        specifications: [{ key: 'Fabric', value: '53% Cotton, 47% Polyester Tech Fleece' }],
        description: 'Smooth on both sides, this Tech Fleece delivers premium lightweight thermal insulation without excess bulk.',
      },
      {
        name: 'Birkenstock Boston Oiled Leather Clogs (Habana)',
        brand: 'Birkenstock',
        category: catMap['footwear-and-sneakers']._id,
        categoryName: 'Footwear & Sneakers',
        subcategory: 'Casual Shoes',
        price: 155.00,
        originalPrice: 170.00,
        discount: 9,
        image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&auto=format&fit=crop&q=80',
        stock: 24,
        sku: 'BRK-BSTN-HBN',
        rating: 4.9,
        reviewCount: 420,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: false,
        isNew: false,
        offerText: 'Anatomically shaped original cork-latex footbed',
        specifications: [{ key: 'Upper', value: 'Oiled Nubuck Leather' }, { key: 'Sole', value: 'Flexible EVA' }],
        description: 'A legendary slip-on classic providing supreme orthopedic foot support and effortless European style.',
      },
      {
        name: 'Breville Barista Touch Impress Espresso Machine',
        brand: 'Breville',
        category: catMap['smart-home-and-appliances']._id,
        categoryName: 'Smart Home & Appliances',
        subcategory: 'Coffee & Kitchen',
        price: 1299.95,
        originalPrice: 1499.95,
        discount: 13,
        image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
        stock: 8,
        sku: 'BRV-BES881-SST',
        rating: 4.9,
        reviewCount: 88,
        isFeatured: false,
        isPremium: true,
        isTrending: false,
        isDeal: true,
        isNew: true,
        offerText: 'Step-by-step barista guidance with automated microfoam',
        specifications: [{ key: 'System', value: 'ThermoJet 3-second heat up' }, { key: 'Tamping', value: 'Assisted 10kg Tamp with 7° twist' }],
        description: 'Third-wave specialty coffee made simple with touchscreen swipe, real-time dosing feedback, and automated microfoam.',
      },
      {
        name: 'Stanley Quencher H2.0 FlowState Insulated Tumbler (40oz)',
        brand: 'Stanley',
        category: catMap['sports-and-fitness']._id,
        categoryName: 'Sports & Fitness',
        subcategory: 'Hydration',
        price: 45.00,
        originalPrice: 50.00,
        discount: 10,
        image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
        stock: 60,
        sku: 'STN-QNCH-40OZ',
        rating: 4.8,
        reviewCount: 890,
        isFeatured: true,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Keeps beverages ice cold for up to 48 hours',
        specifications: [{ key: 'Material', value: '90% Recycled 18/8 Stainless Steel' }, { key: 'Lid', value: 'FlowState 3-position rotating lid' }],
        description: 'The viral hydration companion featuring double-wall vacuum insulation and comfort-grip handle.',
      },
      {
        name: 'Casio G-Shock GA-B2100 Tough Solar Bluetooth',
        brand: 'Casio',
        category: catMap['fashion-and-apparel']._id,
        categoryName: 'Fashion & Apparel',
        subcategory: 'Watches',
        price: 139.99,
        originalPrice: 160.00,
        discount: 13,
        image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80',
        stock: 35,
        sku: 'CAS-GAB2100-1A',
        rating: 4.8,
        reviewCount: 350,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: 'Solar Powered with Smartphone Bluetooth link',
        specifications: [{ key: 'Structure', value: 'Carbon Core Guard' }, { key: 'Water Resistance', value: '200M ISO' }],
        description: 'The ultra-popular "CasiOak" octagonal design enhanced with Tough Solar power and automatic Bluetooth time sync.',
      },
      {
        name: 'Ninja Foodi Smart XL 6-in-1 Indoor Grill with Air Fry',
        brand: 'Ninja',
        category: catMap['smart-home-and-appliances']._id,
        categoryName: 'Smart Home & Appliances',
        subcategory: 'Kitchen Appliances',
        price: 219.99,
        originalPrice: 279.99,
        discount: 21,
        image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
        stock: 20,
        sku: 'NNJ-FG551-GRL',
        rating: 4.8,
        reviewCount: 290,
        isFeatured: false,
        isPremium: false,
        isTrending: true,
        isDeal: true,
        isNew: false,
        offerText: '500°F Cyclonic Grilling with Smart Cook Probe',
        specifications: [{ key: 'Functions', value: 'Grill, Air Crisp, Roast, Bake, Broil, Dehydrate' }],
        description: 'Sear, sizzle, and air fry with the precision of a built-in Foodi thermometer for perfect doneness without guessing.',
      },
    ];

    const allProducts = [...productsData, ...extraProducts];
    const insertedProducts = await Product.insertMany(allProducts);
    console.log(`[Seed] Successfully inserted ${insertedProducts.length} rich products!`);

    // Seed Users
    console.log('[Seed] Seeding Administrator and Customer accounts...');
    const adminUser = await User.create({
      name: 'SHOPORA Operations Admin',
      email: 'admin@shopora.com',
      password: 'Admin@12345',
      role: 'admin',
      phone: '+1 (555) 019-2834',
      isActive: true,
      addresses: [
        {
          fullName: 'SHOPORA Fulfillment Headquarters',
          phone: '+1 (555) 019-2834',
          addressLine1: '100 Innovation Parkway, Suite 900',
          city: 'San Jose',
          state: 'CA',
          pincode: '95134',
          country: 'United States',
          isDefault: true,
        },
      ],
    });

    const customerUser = await User.create({
      name: 'Alex Johnson',
      email: 'user@shopora.com',
      password: 'User@12345',
      role: 'user',
      phone: '+91 98765 43210',
      isActive: true,
      addresses: [
        {
          fullName: 'Alex Johnson',
          phone: '+91 98765 43210',
          addressLine1: 'Flat 402, Prestige Palms, 12th Main Road, Indiranagar',
          landmark: 'Near 100ft Road Junction',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560038',
          country: 'India',
          addressType: 'Home',
          isDefault: true,
        },
        {
          fullName: 'Alex Johnson (Office)',
          phone: '+91 98765 43210',
          addressLine1: 'RMZ Infinity, Tower D, 4th Floor, Old Madras Road',
          landmark: 'Opposite Benniganahalli Metro Station',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560016',
          country: 'India',
          addressType: 'Work',
          isDefault: false,
        },
        {
          fullName: 'Alex Johnson (US Residence)',
          phone: '+1 (555) 234-5678',
          addressLine1: '742 Evergreen Terrace, Apt 4B',
          city: 'Springfield',
          state: 'OR',
          pincode: '97477',
          country: 'United States',
          addressType: 'Home',
          isDefault: false,
        },
      ],
    });

    // Seed Wishlist for Customer
    await Wishlist.create({
      user: customerUser._id,
      products: [insertedProducts[0]._id, insertedProducts[2]._id, insertedProducts[5]._id],
    });

    // Seed Verified Reviews
    console.log('[Seed] Seeding verified customer reviews...');
    await Review.insertMany([
      {
        product: insertedProducts[0]._id,
        user: customerUser._id,
        userName: customerUser.name,
        rating: 5,
        title: 'Unbelievable performance and battery life',
        comment: 'The titanium finish is remarkably light in hand. Cameras produce cinema-grade depth of field. Delivered in 2 days in mint condition.',
        isVerifiedPurchase: true,
      },
      {
        product: insertedProducts[5]._id,
        user: customerUser._id,
        userName: customerUser.name,
        rating: 5,
        title: 'Workstation powerhouse',
        comment: 'Runs Docker containers, 8K video exports, and heavy IDEs simultaneously without the fans even kicking on. Flawless display.',
        isVerifiedPurchase: true,
      },
      {
        product: insertedProducts[10]._id,
        user: customerUser._id,
        userName: customerUser.name,
        rating: 5,
        title: 'Best noise cancellation on the market',
        comment: 'Silences airplane engine rumble completely. Calls are crystal clear in windy conditions.',
        isVerifiedPurchase: true,
      },
    ]);

    // Seed past order with tracking timeline for Customer
    console.log('[Seed] Seeding past order with tracking timeline...');
    const pastOrder = await Order.create({
      orderNumber: 'SHP-2026-108492',
      user: customerUser._id,
      items: [
        {
          product: insertedProducts[10]._id,
          name: insertedProducts[10].name,
          brand: insertedProducts[10].brand,
          price: insertedProducts[10].originalPrice || 399.99,
          discount: insertedProducts[10].discount || 13,
          finalPrice: insertedProducts[10].price || 348.00,
          quantity: 1,
          image: insertedProducts[10].image,
        },
      ],
      shippingAddress: {
        fullName: customerUser.addresses[0].fullName,
        phone: customerUser.addresses[0].phone,
        addressLine1: customerUser.addresses[0].addressLine1,
        city: customerUser.addresses[0].city,
        state: customerUser.addresses[0].state,
        pincode: customerUser.addresses[0].pincode,
        country: customerUser.addresses[0].country,
      },
      paymentMethod: 'Cash on Delivery',
      paymentStatus: 'Cash on Delivery',
      subtotal: 348.00,
      discount: 51.99,
      shippingFee: 0,
      total: 348.00,
      orderStatus: 'Shipped',
      carrier: 'SHOPORA Prime Express',
      trackingHistory: [
        {
          status: 'Order Placed',
          message: 'Order received and verified by automated checkout system.',
          location: 'SHOPORA Primary Fulfillment Hub',
          timestamp: new Date(Date.now() - 48 * 3600 * 1000),
        },
        {
          status: 'Confirmed',
          message: 'Inventory reserved and confirmed by official brand distributor.',
          location: 'West Coast Logistics Center',
          timestamp: new Date(Date.now() - 36 * 3600 * 1000),
        },
        {
          status: 'Processing',
          message: 'Quality check passed. Package sent to sorting line.',
          location: 'Bay Area Sorting Facility',
          timestamp: new Date(Date.now() - 24 * 3600 * 1000),
        },
        {
          status: 'Packed',
          message: 'Sealed with tamper-evident security tape.',
          location: 'Outbound Bay 4',
          timestamp: new Date(Date.now() - 16 * 3600 * 1000),
        },
        {
          status: 'Shipped',
          message: 'In transit with SHOPORA Prime Express carrier.',
          location: 'En route to Springfield Delivery Center',
          timestamp: new Date(Date.now() - 6 * 3600 * 1000),
        },
      ],
    });

    // Seed Notification
    await Notification.create({
      user: customerUser._id,
      title: 'Order Dispatched: #SHP-2026-108492',
      message: 'Your Sony WH-1000XM5 headphones are in transit with SHOPORA Prime Express.',
      type: 'order',
      link: `/pages/order-tracking.html?orderId=${pastOrder._id}`,
    });

    // Seed Promotional Offers
    console.log('[Seed] Seeding promotional Offers linked to products...');
    const flashProducts = insertedProducts.filter((p) => p.isDeal || p.discount >= 15).slice(0, 8);
    const techProducts = insertedProducts.filter((p) => p.categoryName === 'Laptops & Computing' || p.categoryName === 'Mobiles & Tablets').slice(0, 8);
    const selectProducts = insertedProducts.filter((p) => p.isPremium || p.price > 700).slice(0, 8);
    const audioProducts = insertedProducts.filter((p) => p.categoryName === 'Audio & Headphones').slice(0, 8);
    const homeProducts = insertedProducts.filter((p) => p.categoryName === 'Smart Home & Appliances').slice(0, 8);
    const bankProducts = insertedProducts.slice(0, 8);

    const offersData = [
      {
        title: '⚡ Flash Sale — Up to 40% OFF',
        subtitle: 'Save more on your everyday flagship tech & smart accessories',
        type: 'FLASH DEAL',
        badgeText: 'FLASH DEAL',
        bannerImage: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=1400&auto=format&fit=crop&q=80',
        discountType: 'percentage',
        discountValue: 40,
        tagline: 'Expires in limited hours',
        ctaText: 'SHOP FLASH SALE',
        ctaLink: '/pages/products.html?deal=flash',
        startTime: new Date(),
        endTime: new Date(Date.now() + 24 * 3600 * 1000), // 24 hours from now
        category: 'Electronics',
        products: flashProducts.map((p) => p._id),
        isActive: true,
        priority: 10,
      },
      {
        title: '🔥 Deals of the Day',
        subtitle: 'Exclusive 24-hour markdowns on workstations & computing power',
        type: 'DEAL OF THE DAY',
        badgeText: 'DEAL OF THE DAY',
        bannerImage: 'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?w=1400&auto=format&fit=crop&q=80',
        discountType: 'percentage',
        discountValue: 35,
        tagline: 'Refreshed every 24 hours',
        ctaText: 'EXPLORE DEALS',
        ctaLink: '/pages/products.html?deal=today',
        startTime: new Date(),
        endTime: new Date(Date.now() + 48 * 3600 * 1000),
        category: 'Laptops',
        products: techProducts.map((p) => p._id),
        isActive: true,
        priority: 9,
      },
      {
        title: '✨ SHOPORA SELECT — Luxury Edition',
        subtitle: 'Premium products, thoughtfully selected with white-glove concierge delivery',
        type: 'PREMIUM OFFER',
        badgeText: 'SHOPORA SELECT',
        bannerImage: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=1400&auto=format&fit=crop&q=80',
        discountType: 'percentage',
        discountValue: 20,
        tagline: 'Curated by master stylists',
        ctaText: 'EXPLORE COLLECTION',
        ctaLink: '/pages/products.html?premium=true',
        startTime: new Date(),
        endTime: new Date(Date.now() + 7 * 24 * 3600 * 1000),
        category: 'Premium',
        products: selectProducts.map((p) => p._id),
        isActive: true,
        priority: 8,
      },
      {
        title: '🎧 Weekend Audio Fest',
        subtitle: 'Studio acoustics, active noise cancellation, and high-res audio setups',
        type: 'WEEKEND OFFER',
        badgeText: 'WEEKEND SPECIAL',
        bannerImage: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1400&auto=format&fit=crop&q=80',
        discountType: 'percentage',
        discountValue: 30,
        tagline: 'Pure sound excellence',
        ctaText: 'DISCOVER AUDIO',
        ctaLink: '/pages/products.html?category=audio-and-headphones',
        startTime: new Date(),
        endTime: new Date(Date.now() + 72 * 3600 * 1000),
        category: 'Audio',
        products: audioProducts.map((p) => p._id),
        isActive: true,
        priority: 7,
      },
      {
        title: '💙 Instant 10% Bank Discount',
        subtitle: 'Extra 10% instant checkout discount on HDFC, ICICI, and SBI cards',
        type: 'BANK OFFER',
        badgeText: 'BANK OFFER',
        bannerImage: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1400&auto=format&fit=crop&q=80',
        discountType: 'percentage',
        discountValue: 10,
        tagline: 'Min order $100',
        ctaText: 'CLAIM BANK OFFER',
        ctaLink: '/pages/products.html?hasDiscount=true',
        startTime: new Date(),
        endTime: new Date(Date.now() + 10 * 24 * 3600 * 1000),
        category: 'All',
        products: bankProducts.map((p) => p._id),
        isActive: true,
        priority: 6,
      },
      {
        title: '🏠 Smart Home & Appliances Fair',
        subtitle: 'Intelligent robot vacuums, espresso makers, and air quality systems',
        type: 'CATEGORY OFFER',
        badgeText: 'SMART LIVING',
        bannerImage: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1400&auto=format&fit=crop&q=80',
        discountType: 'percentage',
        discountValue: 25,
        tagline: 'Modernize every room',
        ctaText: 'SHOP APPLIANCES',
        ctaLink: '/pages/products.html?category=smart-home-and-appliances',
        startTime: new Date(),
        endTime: new Date(Date.now() + 5 * 24 * 3600 * 1000),
        category: 'Home',
        products: homeProducts.map((p) => p._id),
        isActive: true,
        priority: 5,
      },
    ];

    const insertedOffers = await Offer.insertMany(offersData);
    console.log(`[Seed] Successfully seeded ${insertedOffers.length} promotional Offers!`);

    console.log('\n========================================================');
    console.log('🎉 SHOPORA DATABASE SEEDING COMPLETED SUCCESSFULLY!');
    console.log(`   - Categories: ${insertedCategories.length}`);
    console.log(`   - Products: ${insertedProducts.length}`);
    console.log('   - Administrator: admin@shopora.com / Admin@12345');
    console.log('   - Customer: user@shopora.com / User@12345');
    console.log('========================================================\n');

    process.exit(0);
  } catch (error) {
    console.error(`[Seed Error]: ${error.message}`);
    process.exit(1);
  }
};

seedDatabase();
